name: CI

on:
  push:
    branches:
    - latest
  pull_request:
    branches:
      - latest

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'
    - name: Fetch parser
      run: |
        mkdir -p downloaded_parser
        curl -L "$(python3 ./tools/get_latest_parser_url.py)" -o downloaded_parser/snooty.zip
        cd downloaded_parser && unzip snooty.zip
    - name: Test parser
      run: mkdir empty && ./downloaded_parser/snooty/snooty build --rstspec=snooty/rstspec.toml empty/
